- hosts: 3.85.159.63
  tasks:
  - name: Restart all services
    shell: echo "Restarting all services"
    notify: restart 3.85.159.63

  handlers:
  - name: Restart sshd
    service:
      name: sshd
      state: restarted
      enabled: yes
    listen: "restart 3.85.159.63"

  - name: Restart ntpd
    service:
      name: ntpd
      state: restarted
      enabled: yes
    listen: "restart 3.85.159.63"
